name: Weekly Replicate Report

on:
  schedule:
    # Runs every Monday at 9:00 AM UTC (adjust for your timezone)
    - cron: "0 9 * * MON"
  
  # Allow manual triggering
  workflow_dispatch:

jobs:
  send-report:
    runs-on: ubuntu-latest
    environment: secrets
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Generate and send weekly report
        run: npm run report
        env:
          TO_EMAILS: ${{ secrets.TO_EMAILS }}
          FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}